db.createCollection('plans');

db.plans.createIndex({ 'baseentity._id': 1 }, { unique: true });

db.plans.insertMany([
  {
    baseentity: {
      _id: UUID('66bcfccc-2f92-4db9-a8dc-a0bcaaaf814c'),
      visibility_level: 4,
      visibility_type: 8,
      resource_owner: {
        tenant_id: UUID('a3a80810-f91c-4391-9eff-6d47a13bebde'),
        client_id: UUID('ff96c01f-a741-4429-a0cd-2868d408c42f'),
        group_id: UUID('1f743a05-03c7-471d-a6e9-de92d7097881'),
        user_id: UUID('c8e9301d-8d3d-4668-a7a1-a46fe813e9ed'),
      },
      created_at: new Date('2025-02-05T16:07:17.454+00:00'),
      updated_at: new Date('2025-02-05T16:07:17.454+00:00'),
    },
    name: 'Starter Pack',
    description: 'Kickstart your journey with essential features for free.',
    kind: 'starter',
    customer_type: 'individual',
    prices: {
      monthly: [
        {
          amount: 0.00,
          currency: 'USD',
          total_discount: 0.00,
          discount_percentage: 0,
        },
        {
          amount: 0.00,
          currency: 'EUR',
          total_discount: 0.00,
          discount_percentage: 0,
        },
      ],
      yearly: [
        {
          amount: 0.00,
          currency: 'USD',
          total_discount: 0.00,
          discount_percentage: 0,
        },
        {
          amount: 0.00,
          currency: 'EUR',
          total_discount: 0.00,
          discount_percentage: 0,
        },
      ],
    },
    operation_limits: {
      UploadReplayFiles: {
        name: 'Upload Replay Files',
        description: 'Maximum number of replay files you can upload.',
        limit: 5,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      StorageLimit: {
        name: 'Storage Limit',
        description: 'Total storage space available for your files.',
        limit: 500,
        display_unit_type: 'bytes',
        display_unit: 'MB',
        display_unit_position: 'after',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAnalytics: {
        name: 'Analytics',
        description: 'Access to basic analytics features.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureChatAndComments: {
        name: 'Chat and Comments',
        description: 'Engage with the community through chat and comments.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureForum: {
        name: 'Community Forum',
        description: 'Participate in community discussions through forums.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAchievements: {
        name: 'Achievements',
        description: 'Unlock and track your achievements.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
    },
    is_free: true,
    is_available: true,
    is_legacy: false,
    is_active: true,
    display_priority_score: 1,
    regions: ['US', 'EU'],
    languages: ['en', 'es'],
    effective_date: new Date('2025-02-05T00:00:00Z'),
    expiration_date: null,
  },
  {
    baseentity: {
      _id: UUID('f2c0f8a1-7d8c-4b2d-8b6f-1f5b5e4c3b3c'),
      visibility_level: 4,
      visibility_type: 8,
      resource_owner: {
        tenant_id: UUID('a3a80810-f91c-4391-9eff-6d47a13bebde'),
        client_id: UUID('ff96c01f-a741-4429-a0cd-2868d408c42f'),
        group_id: UUID('1f743a05-03c7-471d-a6e9-de92d7097881'),
        user_id: UUID('c8e9301d-8d3d-4668-a7a1-a46fe813e9ed'),
      },
      created_at: new Date('2025-02-05T16:07:17.454+00:00'),
      updated_at: new Date('2025-02-05T16:07:17.454+00:00'),
    },
    name: 'Pro Pack',
    description: 'Unlock advanced features to take your experience to the next level.',
    kind: 'pro',
    customer_type: 'individual',
    prices: {
      monthly: [
        {
          amount: 9.99,
          currency: 'USD',
          total_discount: 8.99,
          discount_percentage: 10,
        },
        {
          amount: 8.99,
          currency: 'EUR',
          total_discount: 8.09,
          discount_percentage: 10,
        },
      ],
      yearly: [
        {
          amount: 99.99,
          currency: 'USD',
          total_discount: 84.99,
          discount_percentage: 15,
        },
        {
          amount: 89.99,
          currency: 'EUR',
          total_discount: 76.49,
          discount_percentage: 15,
        },
      ],
    },
    operation_limits: {
      UploadReplayFiles: {
        name: 'Upload Replay Files',
        description: 'Maximum number of replay files you can upload.',
        limit: 20,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      StorageLimit: {
        name: 'Storage Limit',
        description: 'Total storage space available for your files.',
        limit: 5000,
        display_unit_type: 'bytes',
        display_unit: 'MB',
        display_unit_position: 'after',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAnalytics: {
        name: 'Analytics',
        description: 'Access to advanced analytics features.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureChatAndComments: {
        name: 'Chat and Comments',
        description: 'Engage with the community through chat and comments.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureForum: {
        name: 'Community Forum',
        description: 'Participate in community discussions through forums.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAchievements: {
        name: 'Achievements',
        description: 'Unlock and track your achievements.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
    },
    is_free: false,
    is_available: true,
    is_legacy: false,
    is_active: true,
    display_priority_score: 2,
    regions: ['US', 'EU'],
    languages: ['en', 'es'],
    effective_date: new Date('2025-02-05T00:00:00Z'),
    expiration_date: null,
  },
  {
    baseentity: {
      _id: UUID('d6c8e4e4-4d6d-4a2b-8c7f-9e4c7b4e3d6c'),
      visibility_level: 4,
      visibility_type: 8,
      resource_owner: {
        tenant_id: UUID('a3a80810-f91c-4391-9eff-6d47a13bebde'),
        client_id: UUID('ff96c01f-a741-4429-a0cd-2868d408c42f'),
        group_id: UUID('1f743a05-03c7-471d-a6e9-de92d7097881'),
        user_id: UUID('c8e9301d-8d3d-4668-a7a1-a46fe813e9ed'),
      },
      created_at: new Date('2025-02-05T16:07:17.454+00:00'),
      updated_at: new Date('2025-02-05T16:07:17.454+00:00'),
    },
    name: 'Elite Pack',
    description: 'Experience the ultimate features and services for the most demanding users.',
    kind: 'business',
    customer_type: 'individual',
    prices: {
      monthly: [
        {
          amount: 19.99,
          currency: 'USD',
          total_discount: 15.99,
          discount_percentage: 20,
        },
        {
          amount: 17.99,
          currency: 'EUR',
          total_discount: 14.39,
          discount_percentage: 20,
        },
      ],
      yearly: [
        {
          amount: 199.99,
          currency: 'USD',
          total_discount: 149.99,
          discount_percentage: 25,
        },
        {
          amount: 179.99,
          currency: 'EUR',
          total_discount: 134.99,
          discount_percentage: 25,
        },
      ],
    },
    operation_limits: {
      UploadReplayFiles: {
        name: 'Upload Replay Files',
        description: 'Maximum number of replay files you can upload.',
        limit: 50,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      StorageLimit: {
        name: 'Storage Limit',
        description: 'Total storage space available for your files.',
        limit: 10000,
        display_unit_type: 'bytes',
        display_unit: 'MB',
        display_unit_position: 'after',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAnalytics: {
        name: 'Analytics',
        description: 'Access to premium analytics features.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureChatAndComments: {
        name: 'Chat and Comments',
        description: 'Engage with the community through chat and comments.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureForum: {
        name: 'Community Forum',
        description: 'Participate in community discussions through forums.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAchievements: {
        name: 'Achievements',
        description: 'Unlock and track your achievements.',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
    },
    is_free: false,
    is_available: true,
    is_legacy: false,
    is_active: true,
    display_priority_score: 3,
    regions: ['US', 'EU'],
    languages: ['en', 'es'],
    effective_date: new Date('2025-02-05T00:00:00Z'),
    expiration_date: null,
  },
]);
