db.createCollection('plans');

db.plans.createIndex({ 'baseentity._id': 1 }, { unique: true });
db.plans.createIndex({ 'kind': 1 });
db.plans.createIndex({ 'is_active': 1 });
db.plans.createIndex({ 'is_free': 1 });

// Well-known UUIDs for plans (stable across environments)
const PLAN_FREE_ID = UUID('00000000-0000-0000-0001-000000000001');
const PLAN_PRO_ID = UUID('00000000-0000-0000-0001-000000000002');
const PLAN_TEAM_ID = UUID('00000000-0000-0000-0001-000000000003');
const PLAN_ORGANIZER_ID = UUID('00000000-0000-0000-0001-000000000004');

// System resource owner for plans
const SYSTEM_TENANT_ID = UUID('00000000-0000-0000-0000-000000000001');
const SYSTEM_CLIENT_ID = UUID('00000000-0000-0000-0000-000000000002');
const SYSTEM_USER_ID = UUID('00000000-0000-0000-0000-000000000003');

db.plans.insertMany([
  // ============================================================================
  // FREE TIER - Casual Gamers & Trial Users
  // ============================================================================
  {
    baseentity: {
      _id: PLAN_FREE_ID,
      visibility_level: 4,
      visibility_type: 8,
      resource_owner: {
        tenant_id: SYSTEM_TENANT_ID,
        client_id: SYSTEM_CLIENT_ID,
        group_id: SYSTEM_USER_ID,
        user_id: SYSTEM_USER_ID,
      },
      created_at: new Date('2025-01-01T00:00:00Z'),
      updated_at: new Date('2025-01-01T00:00:00Z'),
    },
    name: 'Free',
    description: 'Perfect for casual players exploring competitive gaming. Access core features and community.',
    kind: 'free',
    customer_type: 'individual',
    prices: {
      monthly: [
        { amount: 0, currency: 'USD', total_discount: 0, discount_percentage: 0 },
        { amount: 0, currency: 'EUR', total_discount: 0, discount_percentage: 0 },
        { amount: 0, currency: 'BRL', total_discount: 0, discount_percentage: 0 },
      ],
      yearly: [
        { amount: 0, currency: 'USD', total_discount: 0, discount_percentage: 0 },
        { amount: 0, currency: 'EUR', total_discount: 0, discount_percentage: 0 },
        { amount: 0, currency: 'BRL', total_discount: 0, discount_percentage: 0 },
      ],
    },
    operation_limits: {
      // REPLAY & CLOUD STORAGE
      UploadReplayFiles: {
        name: 'Replay Uploads',
        description: 'Number of replay files you can upload per month',
        limit: 5,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '/month',
      },
      StorageLimit: {
        name: 'Cloud Storage',
        description: 'Total cloud storage for replays and media',
        limit: 500,
        display_unit_type: 'bytes',
        display_unit: 'MB',
        display_unit_position: 'after',
        prefix_string: '',
        suffix_string: '',
      },
      MediaAlbum: {
        name: 'Media Albums',
        description: 'Create albums for clips and highlights',
        limit: 1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },

      // SQUAD & PLAYER MANAGEMENT
      CreateSquadProfile: {
        name: 'Squad Profiles',
        description: 'Number of squads you can create',
        limit: 1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      PlayersPerSquadAmount: {
        name: 'Players per Squad',
        description: 'Maximum team members per squad',
        limit: 5,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' players',
      },
      CreatePlayerProfile: {
        name: 'Player Profiles',
        description: 'Number of player profiles you can manage',
        limit: 1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },

      // MATCHMAKING
      MatchMakingQueueAmount: {
        name: 'Matchmaking Queue',
        description: 'Access to matchmaking queues',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Casual ',
        suffix_string: ' only',
      },
      MatchMakingPriorityQueue: {
        name: 'Priority Queue',
        description: 'Skip the line with priority matchmaking',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      MatchMakingCreateAmount: {
        name: 'Custom Lobbies',
        description: 'Create custom match lobbies',
        limit: 0,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },

      // TOURNAMENTS
      FeatureTournament: {
        name: 'Tournament Access',
        description: 'Participate in community tournaments',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Community ',
        suffix_string: ' only',
      },
      TournamentProfileAmount: {
        name: 'Host Tournaments',
        description: 'Create and host tournaments',
        limit: 0,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },

      // ANALYTICS & FEATURES
      FeatureAnalytics: {
        name: 'Analytics',
        description: 'Access to performance analytics',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Basic ',
        suffix_string: '',
      },
      FeatureChatAndComments: {
        name: 'Chat & Comments',
        description: 'Community interaction features',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureForum: {
        name: 'Community Forum',
        description: 'Access to community discussions',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAchievements: {
        name: 'Achievements',
        description: 'Track and display achievements',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },

      // PREMIUM FEATURES (NOT AVAILABLE IN FREE)
      AdFreeExperience: {
        name: 'Ad-Free Experience',
        description: 'Browse without advertisements',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAPI: {
        name: 'API Access',
        description: 'Programmatic access to your data',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureWebhooks: {
        name: 'Webhooks',
        description: 'Real-time event notifications',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      DiscordIntegration: {
        name: 'Discord Integration',
        description: 'Connect with Discord server',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      PremiumSupport: {
        name: 'Priority Support',
        description: 'Priority customer support',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      EarlyAccessFeatures: {
        name: 'Early Access',
        description: 'Access to beta features',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      ExclusiveContent: {
        name: 'Exclusive Content',
        description: 'Pro-only guides and content',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureBetting: {
        name: 'Wager Matches',
        description: 'Skill-based wager matches',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureGlobalWallet: {
        name: 'Wallet & Payouts',
        description: 'Receive prize money and payments',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
    },
    is_free: true,
    is_available: true,
    is_legacy: false,
    is_active: true,
    display_priority_score: 1,
    regions: ['US', 'EU', 'BR', 'LATAM', 'SEA', 'OCE'],
    languages: ['en', 'es', 'pt', 'de', 'fr'],
    effective_date: new Date('2025-01-01T00:00:00Z'),
    expiration_date: null,
  },

  // ============================================================================
  // PRO TIER - Competitive Players ($9.99/month)
  // ============================================================================
  {
    baseentity: {
      _id: PLAN_PRO_ID,
      visibility_level: 4,
      visibility_type: 8,
      resource_owner: {
        tenant_id: SYSTEM_TENANT_ID,
        client_id: SYSTEM_CLIENT_ID,
        group_id: SYSTEM_USER_ID,
        user_id: SYSTEM_USER_ID,
      },
      created_at: new Date('2025-01-01T00:00:00Z'),
      updated_at: new Date('2025-01-01T00:00:00Z'),
    },
    name: 'Pro',
    description: 'For competitive players serious about improving. Advanced analytics, priority matchmaking, and no ads.',
    kind: 'pro',
    customer_type: 'individual',
    prices: {
      monthly: [
        { amount: 9.99, currency: 'USD', total_discount: 0, discount_percentage: 0 },
        { amount: 8.99, currency: 'EUR', total_discount: 0, discount_percentage: 0 },
        { amount: 39.90, currency: 'BRL', total_discount: 0, discount_percentage: 0 },
      ],
      yearly: [
        { amount: 95.88, currency: 'USD', total_discount: 24.00, discount_percentage: 20 },
        { amount: 86.28, currency: 'EUR', total_discount: 21.60, discount_percentage: 20 },
        { amount: 382.80, currency: 'BRL', total_discount: 96.00, discount_percentage: 20 },
      ],
    },
    operation_limits: {
      // REPLAY & CLOUD STORAGE
      UploadReplayFiles: {
        name: 'Replay Uploads',
        description: 'Unlimited replay file uploads',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },
      StorageLimit: {
        name: 'Cloud Storage',
        description: 'Total cloud storage for replays and media',
        limit: 25000,
        display_unit_type: 'bytes',
        display_unit: 'GB',
        display_unit_position: 'after',
        prefix_string: '',
        suffix_string: '',
      },
      MediaAlbum: {
        name: 'Media Albums',
        description: 'Create albums for clips and highlights',
        limit: 10,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' albums',
      },

      // SQUAD & PLAYER MANAGEMENT
      CreateSquadProfile: {
        name: 'Squad Profiles',
        description: 'Number of squads you can create',
        limit: 3,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' squads',
      },
      PlayersPerSquadAmount: {
        name: 'Players per Squad',
        description: 'Maximum team members per squad',
        limit: 10,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' players',
      },
      CreatePlayerProfile: {
        name: 'Player Profiles',
        description: 'Number of player profiles you can manage',
        limit: 5,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' profiles',
      },

      // MATCHMAKING
      MatchMakingQueueAmount: {
        name: 'Matchmaking Queue',
        description: 'Access to all matchmaking queues',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Ranked & ',
        suffix_string: 'Competitive',
      },
      MatchMakingPriorityQueue: {
        name: 'Priority Queue',
        description: 'Skip the line with priority matchmaking',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      MatchMakingCreateAmount: {
        name: 'Custom Lobbies',
        description: 'Create custom match lobbies',
        limit: 5,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' active',
      },

      // TOURNAMENTS
      FeatureTournament: {
        name: 'Tournament Access',
        description: 'Participate in all tournaments',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'All ',
        suffix_string: 'tournaments',
      },
      TournamentProfileAmount: {
        name: 'Host Tournaments',
        description: 'Create and host tournaments',
        limit: 0,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },

      // ANALYTICS & FEATURES
      FeatureAnalytics: {
        name: 'Analytics',
        description: 'Access to advanced performance analytics',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Advanced ',
        suffix_string: '',
      },
      FeatureChatAndComments: {
        name: 'Chat & Comments',
        description: 'Community interaction features',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureForum: {
        name: 'Community Forum',
        description: 'Access to community discussions',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAchievements: {
        name: 'Achievements',
        description: 'Track and display achievements',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },

      // PREMIUM FEATURES
      AdFreeExperience: {
        name: 'Ad-Free Experience',
        description: 'Browse without advertisements',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAPI: {
        name: 'API Access',
        description: 'Programmatic access to your data',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureWebhooks: {
        name: 'Webhooks',
        description: 'Real-time event notifications',
        limit: 0,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      DiscordIntegration: {
        name: 'Discord Integration',
        description: 'Connect with Discord server',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      PremiumSupport: {
        name: 'Priority Support',
        description: 'Priority email support',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Email ',
        suffix_string: '',
      },
      EarlyAccessFeatures: {
        name: 'Early Access',
        description: 'Access to beta features',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      ExclusiveContent: {
        name: 'Exclusive Content',
        description: 'Pro-only guides and content',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureBetting: {
        name: 'Wager Matches',
        description: 'Skill-based wager matches',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureGlobalWallet: {
        name: 'Wallet & Payouts',
        description: 'Receive prize money and payments',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
    },
    is_free: false,
    is_available: true,
    is_legacy: false,
    is_active: true,
    display_priority_score: 2,
    regions: ['US', 'EU', 'BR', 'LATAM', 'SEA', 'OCE'],
    languages: ['en', 'es', 'pt', 'de', 'fr'],
    effective_date: new Date('2025-01-01T00:00:00Z'),
    expiration_date: null,
  },

  // ============================================================================
  // TEAM TIER - Esports Teams ($29.99/month for 5 seats)
  // ============================================================================
  {
    baseentity: {
      _id: PLAN_TEAM_ID,
      visibility_level: 4,
      visibility_type: 8,
      resource_owner: {
        tenant_id: SYSTEM_TENANT_ID,
        client_id: SYSTEM_CLIENT_ID,
        group_id: SYSTEM_USER_ID,
        user_id: SYSTEM_USER_ID,
      },
      created_at: new Date('2025-01-01T00:00:00Z'),
      updated_at: new Date('2025-01-01T00:00:00Z'),
    },
    name: 'Team',
    description: 'Everything your esports team needs. Team analytics, scrim scheduling, opponent research, and shared resources.',
    kind: 'team',
    customer_type: 'group',
    prices: {
      monthly: [
        { amount: 29.99, currency: 'USD', total_discount: 0, discount_percentage: 0 },
        { amount: 26.99, currency: 'EUR', total_discount: 0, discount_percentage: 0 },
        { amount: 119.90, currency: 'BRL', total_discount: 0, discount_percentage: 0 },
      ],
      yearly: [
        { amount: 287.88, currency: 'USD', total_discount: 72.00, discount_percentage: 20 },
        { amount: 259.08, currency: 'EUR', total_discount: 64.80, discount_percentage: 20 },
        { amount: 1150.80, currency: 'BRL', total_discount: 288.00, discount_percentage: 20 },
      ],
    },
    operation_limits: {
      // REPLAY & CLOUD STORAGE
      UploadReplayFiles: {
        name: 'Replay Uploads',
        description: 'Unlimited replay file uploads',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },
      StorageLimit: {
        name: 'Cloud Storage',
        description: 'Shared team cloud storage',
        limit: 100000,
        display_unit_type: 'bytes',
        display_unit: 'GB',
        display_unit_position: 'after',
        prefix_string: '',
        suffix_string: '',
      },
      MediaAlbum: {
        name: 'Media Albums',
        description: 'Create shared albums for clips and highlights',
        limit: 50,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' albums',
      },

      // SQUAD & PLAYER MANAGEMENT
      CreateSquadProfile: {
        name: 'Squad Profiles',
        description: 'Manage multiple rosters and squads',
        limit: 10,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' squads',
      },
      PlayersPerSquadAmount: {
        name: 'Players per Squad',
        description: 'Maximum team members per squad',
        limit: 25,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' players',
      },
      CreatePlayerProfile: {
        name: 'Team Seats',
        description: 'Included team member seats',
        limit: 10,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: ' seats included',
      },

      // MATCHMAKING
      MatchMakingQueueAmount: {
        name: 'Matchmaking Queue',
        description: 'Access to all matchmaking queues',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'All ',
        suffix_string: 'queues',
      },
      MatchMakingPriorityQueue: {
        name: 'Priority Queue',
        description: 'Team priority matchmaking',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Team ',
        suffix_string: '',
      },
      MatchMakingCreateAmount: {
        name: 'Custom Lobbies',
        description: 'Create custom match lobbies for scrims',
        limit: 25,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: ' active',
      },

      // TOURNAMENTS
      FeatureTournament: {
        name: 'Tournament Access',
        description: 'Participate in all tournaments as a team',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'All ',
        suffix_string: 'tournaments',
      },
      TournamentProfileAmount: {
        name: 'Host Tournaments',
        description: 'Host team-organized tournaments',
        limit: 3,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Up to ',
        suffix_string: '/month',
      },

      // ANALYTICS & FEATURES
      FeatureAnalytics: {
        name: 'Analytics',
        description: 'Team analytics dashboard with opponent research',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Team ',
        suffix_string: 'Dashboard',
      },
      FeatureChatAndComments: {
        name: 'Chat & Comments',
        description: 'Team chat and communication',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureForum: {
        name: 'Community Forum',
        description: 'Access to community discussions',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAchievements: {
        name: 'Achievements',
        description: 'Team achievements and badges',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Team ',
        suffix_string: '',
      },

      // PREMIUM FEATURES
      AdFreeExperience: {
        name: 'Ad-Free Experience',
        description: 'Browse without advertisements',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureAPI: {
        name: 'API Access',
        description: 'Team API access for integrations',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureWebhooks: {
        name: 'Webhooks',
        description: 'Real-time event notifications',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      DiscordIntegration: {
        name: 'Discord Integration',
        description: 'Full Discord server integration',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Full ',
        suffix_string: '',
      },
      PremiumSupport: {
        name: 'Priority Support',
        description: 'Priority phone & email support',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Phone & ',
        suffix_string: 'Email',
      },
      EarlyAccessFeatures: {
        name: 'Early Access',
        description: 'Access to beta features',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      ExclusiveContent: {
        name: 'Exclusive Content',
        description: 'Team-exclusive guides and content',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureBetting: {
        name: 'Wager Matches',
        description: 'Team wager matches',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureGlobalWallet: {
        name: 'Wallet & Payouts',
        description: 'Team wallet and prize distribution',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Team ',
        suffix_string: '',
      },

      // TEAM-SPECIFIC FEATURES
      FeatureCalendarIntegration: {
        name: 'Scrim Calendar',
        description: 'Schedule and manage scrims',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      SquadProfileBoostAmount: {
        name: 'Team Branding',
        description: 'Custom team branding and profile',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
    },
    is_free: false,
    is_available: true,
    is_legacy: false,
    is_active: true,
    display_priority_score: 3,
    regions: ['US', 'EU', 'BR', 'LATAM', 'SEA', 'OCE'],
    languages: ['en', 'es', 'pt', 'de', 'fr'],
    effective_date: new Date('2025-01-01T00:00:00Z'),
    expiration_date: null,
  },

  // ============================================================================
  // ORGANIZER TIER - Tournament Organizers ($99.99/month)
  // ============================================================================
  {
    baseentity: {
      _id: PLAN_ORGANIZER_ID,
      visibility_level: 4,
      visibility_type: 8,
      resource_owner: {
        tenant_id: SYSTEM_TENANT_ID,
        client_id: SYSTEM_CLIENT_ID,
        group_id: SYSTEM_USER_ID,
        user_id: SYSTEM_USER_ID,
      },
      created_at: new Date('2025-01-01T00:00:00Z'),
      updated_at: new Date('2025-01-01T00:00:00Z'),
    },
    name: 'Organizer',
    description: 'Professional tournament hosting platform. Unlimited tournaments, automated prize distribution, white-label branding, and full API access.',
    kind: 'business',
    customer_type: 'company',
    prices: {
      monthly: [
        { amount: 99.99, currency: 'USD', total_discount: 0, discount_percentage: 0 },
        { amount: 89.99, currency: 'EUR', total_discount: 0, discount_percentage: 0 },
        { amount: 399.90, currency: 'BRL', total_discount: 0, discount_percentage: 0 },
      ],
      yearly: [
        { amount: 959.88, currency: 'USD', total_discount: 240.00, discount_percentage: 20 },
        { amount: 863.88, currency: 'EUR', total_discount: 216.00, discount_percentage: 20 },
        { amount: 3838.80, currency: 'BRL', total_discount: 960.00, discount_percentage: 20 },
      ],
    },
    operation_limits: {
      // REPLAY & CLOUD STORAGE
      UploadReplayFiles: {
        name: 'Replay Uploads',
        description: 'Unlimited replay file uploads',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },
      StorageLimit: {
        name: 'Cloud Storage',
        description: 'Enterprise cloud storage',
        limit: 500000,
        display_unit_type: 'bytes',
        display_unit: 'GB',
        display_unit_position: 'after',
        prefix_string: '',
        suffix_string: '',
      },
      MediaAlbum: {
        name: 'Media Albums',
        description: 'Unlimited media albums',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },

      // SQUAD & PLAYER MANAGEMENT
      CreateSquadProfile: {
        name: 'Squad Profiles',
        description: 'Unlimited squad management',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },
      PlayersPerSquadAmount: {
        name: 'Players per Squad',
        description: 'Unlimited team members',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },
      CreatePlayerProfile: {
        name: 'Staff Seats',
        description: 'Unlimited staff seats',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },

      // MATCHMAKING
      MatchMakingQueueAmount: {
        name: 'Matchmaking Queue',
        description: 'Custom matchmaking pools',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Custom ',
        suffix_string: 'pools',
      },
      MatchMakingPriorityQueue: {
        name: 'Priority Queue',
        description: 'Dedicated priority infrastructure',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Dedicated ',
        suffix_string: '',
      },
      MatchMakingCreateAmount: {
        name: 'Custom Lobbies',
        description: 'Unlimited custom lobbies',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },

      // TOURNAMENTS
      FeatureTournament: {
        name: 'Tournament Access',
        description: 'Full tournament platform access',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Full ',
        suffix_string: 'platform',
      },
      TournamentProfileAmount: {
        name: 'Host Tournaments',
        description: 'Unlimited tournament hosting',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },
      MatchMakingTournamentAmount: {
        name: 'Tournament Matches',
        description: 'Unlimited tournament matches',
        limit: -1,
        display_unit_type: 'count',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Unlimited',
        suffix_string: '',
      },

      // ANALYTICS & FEATURES
      FeatureAnalytics: {
        name: 'Analytics',
        description: 'Enterprise analytics and reporting',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Enterprise ',
        suffix_string: '',
      },
      FeatureChatAndComments: {
        name: 'Chat & Comments',
        description: 'Moderated community features',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      FeatureForum: {
        name: 'Community Forum',
        description: 'Branded community forums',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Branded ',
        suffix_string: '',
      },
      FeatureAchievements: {
        name: 'Achievements',
        description: 'Custom achievement system',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Custom ',
        suffix_string: '',
      },

      // PREMIUM FEATURES
      AdFreeExperience: {
        name: 'Ad-Free Experience',
        description: 'White-label ad-free platform',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'White-label ',
        suffix_string: '',
      },
      FeatureAPI: {
        name: 'API Access',
        description: 'Full API access with higher rate limits',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Full ',
        suffix_string: '',
      },
      FeatureWebhooks: {
        name: 'Webhooks',
        description: 'Advanced webhook integrations',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Advanced ',
        suffix_string: '',
      },
      DiscordIntegration: {
        name: 'Discord Integration',
        description: 'Custom Discord bot integration',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Custom ',
        suffix_string: 'Bot',
      },
      PremiumSupport: {
        name: 'Priority Support',
        description: 'Dedicated account manager',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Dedicated ',
        suffix_string: 'Manager',
      },
      EarlyAccessFeatures: {
        name: 'Early Access',
        description: 'Private beta access',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Private ',
        suffix_string: 'beta',
      },
      ExclusiveContent: {
        name: 'Exclusive Content',
        description: 'White-label content creation',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'White-label ',
        suffix_string: '',
      },
      FeatureBetting: {
        name: 'Wager Matches',
        description: 'Tournament prize pools',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Prize ',
        suffix_string: 'pools',
      },
      FeatureGlobalWallet: {
        name: 'Wallet & Payouts',
        description: 'Automated prize distribution',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Automated ',
        suffix_string: '',
      },

      // ORGANIZER-SPECIFIC FEATURES
      FeatureCalendarIntegration: {
        name: 'Event Calendar',
        description: 'Public event calendar',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Public ',
        suffix_string: '',
      },
      SquadProfileBoostAmount: {
        name: 'White-label Branding',
        description: 'Full white-label customization',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: 'Full ',
        suffix_string: '',
      },
      FeatureStoreCatalogIntegration: {
        name: 'Sponsor Integration',
        description: 'Sponsor branding tools',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      GlobalPaymentProcessingAmount: {
        name: 'Payment Processing',
        description: 'Entry fees and prize payouts',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
      CustomEmails: {
        name: 'Custom Emails',
        description: 'Branded email notifications',
        limit: 1,
        display_unit_type: 'boolean',
        display_unit: '',
        display_unit_position: '',
        prefix_string: '',
        suffix_string: '',
      },
    },
    is_free: false,
    is_available: true,
    is_legacy: false,
    is_active: true,
    display_priority_score: 4,
    regions: ['US', 'EU', 'BR', 'LATAM', 'SEA', 'OCE'],
    languages: ['en', 'es', 'pt', 'de', 'fr'],
    effective_date: new Date('2025-01-01T00:00:00Z'),
    expiration_date: null,
  },
]);

print('Plans seeded successfully!');
print('  - Free: Casual players');
print('  - Pro ($9.99/mo): Competitive players');
print('  - Team ($29.99/mo): Esports teams (10 seats)');
print('  - Organizer ($99.99/mo): Tournament organizers');
