services:
  replay-api:
    container_name: "replay-api"
    build:
      context: ..
      dockerfile: replay-api/cmd/rest-api/Dockerfile.rest-api
    ports:
      - "18080:8080"
    volumes:
      - .blob:/app/replay_files
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - DEV_ENV="docker"
      - MONGO_URI=mongodb://mongodb:27017/replay
      - TMP_APP_REPLAY_FILES="/app/replay_files/"
    networks:
      - svc

  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    ports:
      - "37019:27017"
    volumes:
      - ./.mongodb:/data/db
    networks:
      - default
      - svc
    command:
      ["sh", "-c", "chown -R mongodb:mongodb /data/db && mongod --bind_ip_all"]

networks:
  svc:
    driver: bridge
