// PERFIL DO TORNEIO
// STAKING
// PAYOUT
// BOOST/AD SERVICE
// FEATURED ADS
// FEATURED SQUADS
// FEATURED PLAYERS
// FEATURED TOURNAMENTS
// FEATURED STREAMERS
// FEATURED EVENTS
// BETTING
// WALLET
// STORE
// MATCH-MAKING
// EVENTS!
// RULES, GAMEMODES, MAPS, ETC
// FEATURED NETWORKS (IE: FACEIT)

package squad_entities
