// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/infra/events/schemas/matchmaking_events.proto

package schemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEnvelope follows CloudEvents 1.0 spec (https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md).
// Ensures replay-api and match-making-api agree on payload structure.
type EventEnvelope struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // CloudEvents: id (required) - uniquely identifies the event
	Type        string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`               // CloudEvents: type (required) - e.g. "PlayerQueued", "MatchCompleted"
	Source      string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`           // CloudEvents: source (required) - e.g. "replay-api", "match-making-api"
	Specversion string                 `protobuf:"bytes,4,opt,name=specversion,proto3" json:"specversion,omitempty"` // CloudEvents: specversion (required) - e.g. "1.0"
	Time        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`               // CloudEvents: time (optional) - when the event occurred
	Subject     string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`         // CloudEvents: subject (optional) - e.g. player_id, match_id
	// Extension attributes
	ResourceOwnerId   string `protobuf:"bytes,7,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"`      // RID or owner identifier for multi-tenancy/authorization
	CorrelationId     string `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`              // For distributed tracing
	DataschemaVersion int32  `protobuf:"varint,9,opt,name=dataschema_version,json=dataschemaVersion,proto3" json:"dataschema_version,omitempty"` // Payload schema version for evolution; consumers can handle multiple versions
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventEnvelope) GetSpecversion() string {
	if x != nil {
		return x.Specversion
	}
	return ""
}

func (x *EventEnvelope) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EventEnvelope) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EventEnvelope) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

func (x *EventEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventEnvelope) GetDataschemaVersion() int32 {
	if x != nil {
		return x.DataschemaVersion
	}
	return 0
}

// MatchmakingEvent is the top-level message for Kafka. Combines envelope + typed data (CloudEvents: data).
type MatchmakingEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Envelope *EventEnvelope         `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*MatchmakingEvent_PlayerQueued
	//	*MatchmakingEvent_MatchCreated
	//	*MatchmakingEvent_MatchCompleted
	//	*MatchmakingEvent_RatingsUpdated
	Data          isMatchmakingEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchmakingEvent) Reset() {
	*x = MatchmakingEvent{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingEvent) ProtoMessage() {}

func (x *MatchmakingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingEvent.ProtoReflect.Descriptor instead.
func (*MatchmakingEvent) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{1}
}

func (x *MatchmakingEvent) GetEnvelope() *EventEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *MatchmakingEvent) GetData() isMatchmakingEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MatchmakingEvent) GetPlayerQueued() *PlayerQueuedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_PlayerQueued); ok {
			return x.PlayerQueued
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetMatchCreated() *MatchCreatedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_MatchCreated); ok {
			return x.MatchCreated
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetMatchCompleted() *MatchCompletedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_MatchCompleted); ok {
			return x.MatchCompleted
		}
	}
	return nil
}

func (x *MatchmakingEvent) GetRatingsUpdated() *RatingsUpdatedPayload {
	if x != nil {
		if x, ok := x.Data.(*MatchmakingEvent_RatingsUpdated); ok {
			return x.RatingsUpdated
		}
	}
	return nil
}

type isMatchmakingEvent_Data interface {
	isMatchmakingEvent_Data()
}

type MatchmakingEvent_PlayerQueued struct {
	PlayerQueued *PlayerQueuedPayload `protobuf:"bytes,10,opt,name=player_queued,json=playerQueued,proto3,oneof"`
}

type MatchmakingEvent_MatchCreated struct {
	MatchCreated *MatchCreatedPayload `protobuf:"bytes,11,opt,name=match_created,json=matchCreated,proto3,oneof"`
}

type MatchmakingEvent_MatchCompleted struct {
	MatchCompleted *MatchCompletedPayload `protobuf:"bytes,12,opt,name=match_completed,json=matchCompleted,proto3,oneof"`
}

type MatchmakingEvent_RatingsUpdated struct {
	RatingsUpdated *RatingsUpdatedPayload `protobuf:"bytes,13,opt,name=ratings_updated,json=ratingsUpdated,proto3,oneof"`
}

func (*MatchmakingEvent_PlayerQueued) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_MatchCreated) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_MatchCompleted) isMatchmakingEvent_Data() {}

func (*MatchmakingEvent_RatingsUpdated) isMatchmakingEvent_Data() {}

type PlayerQueuedPayload struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId              string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Region              string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	SkillRange          *SkillRange            `protobuf:"bytes,4,opt,name=skill_range,json=skillRange,proto3,oneof" json:"skill_range,omitempty"`           // Optional: min/max MMR or similar.
	PriorityBoost       *int32                 `protobuf:"varint,5,opt,name=priority_boost,json=priorityBoost,proto3,oneof" json:"priority_boost,omitempty"` // Optional: queue priority.
	TenantId            string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId            string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResourcePermissions []string               `protobuf:"bytes,8,rep,name=resource_permissions,json=resourcePermissions,proto3" json:"resource_permissions,omitempty"` // Optional: e.g. ["read", "write"].
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlayerQueuedPayload) Reset() {
	*x = PlayerQueuedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerQueuedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQueuedPayload) ProtoMessage() {}

func (x *PlayerQueuedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQueuedPayload.ProtoReflect.Descriptor instead.
func (*PlayerQueuedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerQueuedPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerQueuedPayload) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerQueuedPayload) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PlayerQueuedPayload) GetSkillRange() *SkillRange {
	if x != nil {
		return x.SkillRange
	}
	return nil
}

func (x *PlayerQueuedPayload) GetPriorityBoost() int32 {
	if x != nil && x.PriorityBoost != nil {
		return *x.PriorityBoost
	}
	return 0
}

func (x *PlayerQueuedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PlayerQueuedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PlayerQueuedPayload) GetResourcePermissions() []string {
	if x != nil {
		return x.ResourcePermissions
	}
	return nil
}

type SkillRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinMmr        int32                  `protobuf:"varint,1,opt,name=min_mmr,json=minMmr,proto3" json:"min_mmr,omitempty"`
	MaxMmr        int32                  `protobuf:"varint,2,opt,name=max_mmr,json=maxMmr,proto3" json:"max_mmr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillRange) Reset() {
	*x = SkillRange{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRange) ProtoMessage() {}

func (x *SkillRange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRange.ProtoReflect.Descriptor instead.
func (*SkillRange) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{3}
}

func (x *SkillRange) GetMinMmr() int32 {
	if x != nil {
		return x.MinMmr
	}
	return 0
}

func (x *SkillRange) GetMaxMmr() int32 {
	if x != nil {
		return x.MaxMmr
	}
	return 0
}

type MatchCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Players       []*MatchPlayer         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	GameServer    *GameServer            `protobuf:"bytes,3,opt,name=game_server,json=gameServer,proto3" json:"game_server,omitempty"`
	LobbyId       string                 `protobuf:"bytes,4,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCreatedPayload) Reset() {
	*x = MatchCreatedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCreatedPayload) ProtoMessage() {}

func (x *MatchCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCreatedPayload.ProtoReflect.Descriptor instead.
func (*MatchCreatedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{4}
}

func (x *MatchCreatedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchCreatedPayload) GetPlayers() []*MatchPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchCreatedPayload) GetGameServer() *GameServer {
	if x != nil {
		return x.GameServer
	}
	return nil
}

func (x *MatchCreatedPayload) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *MatchCreatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MatchCreatedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type MatchPlayer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PartyId             string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"` // Empty if solo.
	ResourcePermissions []string               `protobuf:"bytes,3,rep,name=resource_permissions,json=resourcePermissions,proto3" json:"resource_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MatchPlayer) Reset() {
	*x = MatchPlayer{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPlayer) ProtoMessage() {}

func (x *MatchPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPlayer.ProtoReflect.Descriptor instead.
func (*MatchPlayer) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{5}
}

func (x *MatchPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MatchPlayer) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *MatchPlayer) GetResourcePermissions() []string {
	if x != nil {
		return x.ResourcePermissions
	}
	return nil
}

type GameServer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Region          string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	ResourceOwnerId string                 `protobuf:"bytes,3,opt,name=resource_owner_id,json=resourceOwnerId,proto3" json:"resource_owner_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameServer) Reset() {
	*x = GameServer{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer) ProtoMessage() {}

func (x *GameServer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer.ProtoReflect.Descriptor instead.
func (*GameServer) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{6}
}

func (x *GameServer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GameServer) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GameServer) GetResourceOwnerId() string {
	if x != nil {
		return x.ResourceOwnerId
	}
	return ""
}

type MatchCompletedPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MatchId            string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIds          []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	WinnerTeamId       string                 `protobuf:"bytes,3,opt,name=winner_team_id,json=winnerTeamId,proto3" json:"winner_team_id,omitempty"` // Empty if draw.
	IsDraw             bool                   `protobuf:"varint,4,opt,name=is_draw,json=isDraw,proto3" json:"is_draw,omitempty"`
	CompletedAtEpochMs int64                  `protobuf:"varint,5,opt,name=completed_at_epoch_ms,json=completedAtEpochMs,proto3" json:"completed_at_epoch_ms,omitempty"`
	TenantId           string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId           string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MatchCompletedPayload) Reset() {
	*x = MatchCompletedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCompletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCompletedPayload) ProtoMessage() {}

func (x *MatchCompletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCompletedPayload.ProtoReflect.Descriptor instead.
func (*MatchCompletedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{7}
}

func (x *MatchCompletedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchCompletedPayload) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchCompletedPayload) GetWinnerTeamId() string {
	if x != nil {
		return x.WinnerTeamId
	}
	return ""
}

func (x *MatchCompletedPayload) GetIsDraw() bool {
	if x != nil {
		return x.IsDraw
	}
	return false
}

func (x *MatchCompletedPayload) GetCompletedAtEpochMs() int64 {
	if x != nil {
		return x.CompletedAtEpochMs
	}
	return 0
}

func (x *MatchCompletedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MatchCompletedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type RatingsUpdatedPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MatchId          string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Deltas           []*PlayerRatingDelta   `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	UpdatedAtEpochMs int64                  `protobuf:"varint,3,opt,name=updated_at_epoch_ms,json=updatedAtEpochMs,proto3" json:"updated_at_epoch_ms,omitempty"`
	TenantId         string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId         string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RatingsUpdatedPayload) Reset() {
	*x = RatingsUpdatedPayload{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingsUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingsUpdatedPayload) ProtoMessage() {}

func (x *RatingsUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingsUpdatedPayload.ProtoReflect.Descriptor instead.
func (*RatingsUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{8}
}

func (x *RatingsUpdatedPayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *RatingsUpdatedPayload) GetDeltas() []*PlayerRatingDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

func (x *RatingsUpdatedPayload) GetUpdatedAtEpochMs() int64 {
	if x != nil {
		return x.UpdatedAtEpochMs
	}
	return 0
}

func (x *RatingsUpdatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RatingsUpdatedPayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type PlayerRatingDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MmrBefore     int32                  `protobuf:"varint,2,opt,name=mmr_before,json=mmrBefore,proto3" json:"mmr_before,omitempty"`
	MmrAfter      int32                  `protobuf:"varint,3,opt,name=mmr_after,json=mmrAfter,proto3" json:"mmr_after,omitempty"`
	Delta         int32                  `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRatingDelta) Reset() {
	*x = PlayerRatingDelta{}
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRatingDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRatingDelta) ProtoMessage() {}

func (x *PlayerRatingDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRatingDelta.ProtoReflect.Descriptor instead.
func (*PlayerRatingDelta) Descriptor() ([]byte, []int) {
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerRatingDelta) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerRatingDelta) GetMmrBefore() int32 {
	if x != nil {
		return x.MmrBefore
	}
	return 0
}

func (x *PlayerRatingDelta) GetMmrAfter() int32 {
	if x != nil {
		return x.MmrAfter
	}
	return 0
}

func (x *PlayerRatingDelta) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

var File_pkg_infra_events_schemas_matchmaking_events_proto protoreflect.FileDescriptor

const file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc = "" +
	"\n" +
	"1pkg/infra/events/schemas/matchmaking_events.proto\x12\x15matchmaking.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x02\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vspecversion\x18\x04 \x01(\tR\vspecversion\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12*\n" +
	"\x11resource_owner_id\x18\a \x01(\tR\x0fresourceOwnerId\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12-\n" +
	"\x12dataschema_version\x18\t \x01(\x05R\x11dataschemaVersion\"\xb4\x03\n" +
	"\x10MatchmakingEvent\x12@\n" +
	"\benvelope\x18\x01 \x01(\v2$.matchmaking.events.v1.EventEnvelopeR\benvelope\x12Q\n" +
	"\rplayer_queued\x18\n" +
	" \x01(\v2*.matchmaking.events.v1.PlayerQueuedPayloadH\x00R\fplayerQueued\x12Q\n" +
	"\rmatch_created\x18\v \x01(\v2*.matchmaking.events.v1.MatchCreatedPayloadH\x00R\fmatchCreated\x12W\n" +
	"\x0fmatch_completed\x18\f \x01(\v2,.matchmaking.events.v1.MatchCompletedPayloadH\x00R\x0ematchCompleted\x12W\n" +
	"\x0fratings_updated\x18\r \x01(\v2,.matchmaking.events.v1.RatingsUpdatedPayloadH\x00R\x0eratingsUpdatedB\x06\n" +
	"\x04data\"\xe8\x02\n" +
	"\x13PlayerQueuedPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12G\n" +
	"\vskill_range\x18\x04 \x01(\v2!.matchmaking.events.v1.SkillRangeH\x00R\n" +
	"skillRange\x88\x01\x01\x12*\n" +
	"\x0epriority_boost\x18\x05 \x01(\x05H\x01R\rpriorityBoost\x88\x01\x01\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\x121\n" +
	"\x14resource_permissions\x18\b \x03(\tR\x13resourcePermissionsB\x0e\n" +
	"\f_skill_rangeB\x11\n" +
	"\x0f_priority_boost\">\n" +
	"\n" +
	"SkillRange\x12\x17\n" +
	"\amin_mmr\x18\x01 \x01(\x05R\x06minMmr\x12\x17\n" +
	"\amax_mmr\x18\x02 \x01(\x05R\x06maxMmr\"\x87\x02\n" +
	"\x13MatchCreatedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12<\n" +
	"\aplayers\x18\x02 \x03(\v2\".matchmaking.events.v1.MatchPlayerR\aplayers\x12B\n" +
	"\vgame_server\x18\x03 \x01(\v2!.matchmaking.events.v1.GameServerR\n" +
	"gameServer\x12\x19\n" +
	"\blobby_id\x18\x04 \x01(\tR\alobbyId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\"x\n" +
	"\vMatchPlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x121\n" +
	"\x14resource_permissions\x18\x03 \x03(\tR\x13resourcePermissions\"m\n" +
	"\n" +
	"GameServer\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12*\n" +
	"\x11resource_owner_id\x18\x03 \x01(\tR\x0fresourceOwnerId\"\xfd\x01\n" +
	"\x15MatchCompletedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12$\n" +
	"\x0ewinner_team_id\x18\x03 \x01(\tR\fwinnerTeamId\x12\x17\n" +
	"\ais_draw\x18\x04 \x01(\bR\x06isDraw\x121\n" +
	"\x15completed_at_epoch_ms\x18\x05 \x01(\x03R\x12completedAtEpochMs\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\"\xdd\x01\n" +
	"\x15RatingsUpdatedPayload\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12@\n" +
	"\x06deltas\x18\x02 \x03(\v2(.matchmaking.events.v1.PlayerRatingDeltaR\x06deltas\x12-\n" +
	"\x13updated_at_epoch_ms\x18\x03 \x01(\x03R\x10updatedAtEpochMs\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\"\x82\x01\n" +
	"\x11PlayerRatingDelta\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"mmr_before\x18\x02 \x01(\x05R\tmmrBefore\x12\x1b\n" +
	"\tmmr_after\x18\x03 \x01(\x05R\bmmrAfter\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\x05R\x05deltaBCZAgithub.com/replay-api/replay-api/pkg/infra/events/schemas;schemasb\x06proto3"

var (
	file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescOnce sync.Once
	file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescData []byte
)

func file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescGZIP() []byte {
	file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescOnce.Do(func() {
		file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc), len(file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc)))
	})
	return file_pkg_infra_events_schemas_matchmaking_events_proto_rawDescData
}

var file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_infra_events_schemas_matchmaking_events_proto_goTypes = []any{
	(*EventEnvelope)(nil),         // 0: matchmaking.events.v1.EventEnvelope
	(*MatchmakingEvent)(nil),      // 1: matchmaking.events.v1.MatchmakingEvent
	(*PlayerQueuedPayload)(nil),   // 2: matchmaking.events.v1.PlayerQueuedPayload
	(*SkillRange)(nil),            // 3: matchmaking.events.v1.SkillRange
	(*MatchCreatedPayload)(nil),   // 4: matchmaking.events.v1.MatchCreatedPayload
	(*MatchPlayer)(nil),           // 5: matchmaking.events.v1.MatchPlayer
	(*GameServer)(nil),            // 6: matchmaking.events.v1.GameServer
	(*MatchCompletedPayload)(nil), // 7: matchmaking.events.v1.MatchCompletedPayload
	(*RatingsUpdatedPayload)(nil), // 8: matchmaking.events.v1.RatingsUpdatedPayload
	(*PlayerRatingDelta)(nil),     // 9: matchmaking.events.v1.PlayerRatingDelta
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_pkg_infra_events_schemas_matchmaking_events_proto_depIdxs = []int32{
	10, // 0: matchmaking.events.v1.EventEnvelope.time:type_name -> google.protobuf.Timestamp
	0,  // 1: matchmaking.events.v1.MatchmakingEvent.envelope:type_name -> matchmaking.events.v1.EventEnvelope
	2,  // 2: matchmaking.events.v1.MatchmakingEvent.player_queued:type_name -> matchmaking.events.v1.PlayerQueuedPayload
	4,  // 3: matchmaking.events.v1.MatchmakingEvent.match_created:type_name -> matchmaking.events.v1.MatchCreatedPayload
	7,  // 4: matchmaking.events.v1.MatchmakingEvent.match_completed:type_name -> matchmaking.events.v1.MatchCompletedPayload
	8,  // 5: matchmaking.events.v1.MatchmakingEvent.ratings_updated:type_name -> matchmaking.events.v1.RatingsUpdatedPayload
	3,  // 6: matchmaking.events.v1.PlayerQueuedPayload.skill_range:type_name -> matchmaking.events.v1.SkillRange
	5,  // 7: matchmaking.events.v1.MatchCreatedPayload.players:type_name -> matchmaking.events.v1.MatchPlayer
	6,  // 8: matchmaking.events.v1.MatchCreatedPayload.game_server:type_name -> matchmaking.events.v1.GameServer
	9,  // 9: matchmaking.events.v1.RatingsUpdatedPayload.deltas:type_name -> matchmaking.events.v1.PlayerRatingDelta
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_infra_events_schemas_matchmaking_events_proto_init() }
func file_pkg_infra_events_schemas_matchmaking_events_proto_init() {
	if File_pkg_infra_events_schemas_matchmaking_events_proto != nil {
		return
	}
	file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[1].OneofWrappers = []any{
		(*MatchmakingEvent_PlayerQueued)(nil),
		(*MatchmakingEvent_MatchCreated)(nil),
		(*MatchmakingEvent_MatchCompleted)(nil),
		(*MatchmakingEvent_RatingsUpdated)(nil),
	}
	file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc), len(file_pkg_infra_events_schemas_matchmaking_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_infra_events_schemas_matchmaking_events_proto_goTypes,
		DependencyIndexes: file_pkg_infra_events_schemas_matchmaking_events_proto_depIdxs,
		MessageInfos:      file_pkg_infra_events_schemas_matchmaking_events_proto_msgTypes,
	}.Build()
	File_pkg_infra_events_schemas_matchmaking_events_proto = out.File
	file_pkg_infra_events_schemas_matchmaking_events_proto_goTypes = nil
	file_pkg_infra_events_schemas_matchmaking_events_proto_depIdxs = nil
}
